server:
  port: 8080

eureka:
  instance:
    preferIpAddress: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server-service:8761/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: ms-client
          uri: lb://ms-client
          predicates:
            - Path=/api/v1/clients/**
        - id: ms-loans
          uri: lb://ms-requestCredit
          predicates:
            - Path=/api/v1/loanType/**
        - id: ms-simulation
          uri: lb://ms-simulation
          predicates:
            - Path=/api/v1/credit/**
