server:
  port: 8080

eureka:
  instance:
    preferIpAddress: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server-service:8761/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors: # Configuración global para habilitar CORS
        cors-configurations:
          '[/**]': # Aplica a todas las rutas del Gateway
            allowedOrigins: '*' # Permite cualquier origen (puedes restringir a tu frontend si es necesario)
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: ms-client
          uri: lb://ms-client # Nombre del servicio en Eureka
          predicates:
            - Path=/api/v1/clients/** # Path que redirige a ms-client
        - id: ms-loans
          uri: lb://ms-requestCredit # Nombre del servicio en Eureka
          predicates:
            - Path=/api/v1/loanType/** # Path que redirige a ms-loans
        - id: ms-simulation
          uri: lb://ms-simulation # Nombre del servicio en Eureka
          predicates:
            - Path=/api/v1/credit/** # Path que redirige a ms-simulation
