server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # Habilita la detección automática de servicios registrados en Eureka
      routes:
        - id: ms-client
          uri: lb://ms-client # Nombre del servicio en Eureka
          predicates:
            - Path=/api/v1/clients/** # Path que redirige a ms-clients
        - id: ms-loans
          uri: lb://ms-requestCredit # Nombre del servicio en Eureka
          predicates:
            - Path=/api/v1/loanType/** # Path que redirige a ms-loans
        - id: ms-simulation
          uri: lb://ms-simulation # Nombre del servicio en Eureka
          predicates:
            - Path=/api/v1/credit/** # Path que redirige a ms-simulation
