server:
  port: 8091
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/msRequestCreditDB
    username: postgres
    password: 13101310
eureka:
  instance:
    preferIpAddress: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/