apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-requestcredit-deployment
  labels:
    app: ms-requestcredit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-requestcredit
  template:
    metadata:
      labels:
        app: ms-requestcredit
    spec:
      containers:
        - name: ms-requestcredit
          image: bbustamante13/ms-requestcredit
          ports:
            - containerPort: 8091
          env:
            - name: SERVER_PORT
              value: "0"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_HOST_REQUEST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_PORT_REQUEST
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_NAME_REQUEST
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: DB_PASSWORD